type("Username.png", "admin")
type("Password.png", "compilerz")
click("1333984910768.png")
wait("WORDPRESSVer.png",20)
hover("1333985696030.png")
click("AddNew.png")
wait("AddNewPost.png",10)
type("Entertitlehe.png", "Free Cups at the Fence!")
type("B1EiE4iiiL.png", "In honor of the gift from Bill, these cups are being given out")
click("BI.png")
type("B1EiE4iiiL.png", "by the fence")
click("BI.png")
type("B1EiE4iiiL.png", ":")